version: "3.8"

services:
  07-ctf-dir-listing-server:
    container_name: 07-ctf-dir-listing-server
    build:
      # Utilisation du Dockerfile présent dans le dossier
      context: ./docker/
      args:
        FENELON_1: ${FENELON_1}
        FENELON_2: ${FENELON_2}
        FENELON_3: ${FENELON_3}

        USER_1: ${USER_1}
        USER_2: ${USER_2}
        USER_3: ${USER_3}
        USER_4: ${USER_4}

        PASSWORD_1: ${PASSWORD_1}
        PASSWORD_2: ${PASSWORD_2}
        PASSWORD_3: ${PASSWORD_3}
        PASSWORD_4: ${PASSWORD_4}

    volumes:
      - ./app:/usr/local/apache2/htdocs/
    ports:
      - 8080:80
    restart: unless-stopped