version: "3.1"

services:
  01-ctf-openssh-server:
    container_name: 01-ctf-openssh-server
    # Nom de l'image
    image: ctf/01-ctf-openssh-server
    build:
      # Utilisation du Dockerfile présent dans le dossier
      context: ./
      args:
        FENELON_1: ${FENELON_1}
        FENELON_2: ${FENELON_2}
        FENELON_3: ${FENELON_3}

        USER_1: ${USER_1}
        USER_2: ${USER_2}
        USER_3: ${USER_3}
        #USER_4: ${USER_4}

        PASSWORD_1: ${PASSWORD_1}
        PASSWORD_2: ${PASSWORD_2}
        PASSWORD_3: ${PASSWORD_3}
        #PASSWORD_4: ${PASSWORD_4}

    volumes:
      # Message de bienvenue affiché à la connexion
      - ./banner-message.txt:/etc/motd
      # Pour avoir accès aux logs
      - ./logs:/var/log
    ports:
      - "2222:22"
    restart: unless-stopped