services:

  03-docker-vulnerable-app-sqlinjection-mysql:
    image: 03-docker-vulnerable-app-sqlinjection-mysql
    container_name: 03-docker-vulnerable-app-sqlinjection-mysql
    restart: unless-stopped
    build:
      context: mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  03-docker-vulnerable-app-sqlinjection-php:
    image: 03-docker-vulnerable-app-sqlinjection-php
    container_name: 03-docker-vulnerable-app-sqlinjection-php
    restart: unless-stopped
    build:
      context: php
      dockerfile: Dockerfile
    depends_on:
      - 03-docker-vulnerable-app-sqlinjection-mysql
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./app:/app
    networks:
      - backend

  03-docker-vulnerable-app-sqlinjection-nginx:
    image: 03-docker-vulnerable-app-sqlinjection-nginx
    container_name: 03-docker-vulnerable-app-sqlinjection-nginx
    restart: unless-stopped
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - 03-docker-vulnerable-app-sqlinjection-mysql
      - 03-docker-vulnerable-app-sqlinjection-php
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
