version: "3.8"

services:
  06-ctf-logs-server:
    container_name: 06-ctf-logs-server
    build:
      # Utilisation du Dockerfile présent dans le dossier
      context: ./
      args:
        FENELON_1: ${FENELON_1}
        FENELON_2: ${FENELON_2}
        FENELON_3: ${FENELON_3}

        USER_1: ${USER_1}
        USER_2: ${USER_2}
        USER_3: ${USER_3}
        USER_4: ${USER_4}

        PASSWORD_1: ${PASSWORD_1}
        PASSWORD_2: ${PASSWORD_2}
        PASSWORD_3: ${PASSWORD_3}
        PASSWORD_4: ${PASSWORD_4}

    volumes:
      # Message de bienvenue affiché à la connexion
      - ./banner-message.txt:/etc/motd
    ports:
      - 2222:22
    restart: unless-stopped

  # Un container pour générer des tentatives de connexion
  06-ctf-logs-client:
    container_name: 06-ctf-logs-client
    build:
      # Utilisation du Dockerfile présent dans le dossier
      context: ./client